version: '2'
services:
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix
  app:
    build: .
    environment:
      - DB_SERVER_HOST=db
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
    ports:
      - "10051:10051"
    depends_on:
      - db
  web:
    image: zabbix/zabbix-web-apache-mysql:ubuntu-3.0-latest
    ports:
      - "8080:80"
    environment:
      - DB_SERVER_HOST=db
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - ZBX_SERVER_HOST=app
      - TZ=America/SAO_PAULO
    depends_on:
      - app
  proxy:
    image: zabbix/zabbix-proxy-sqlite3
    depends_on:
      - app
    environment:
      - ZBX_PROXYMODE=0
      - ZBX_HOSTNAME=zabbix-proxy
      - ZBX_SERVER_HOST=app
      - ZBX_SERVER_PORT=10051
  client_1:
    image: zabbix/zabbix-agent:ubuntu-3.0-latest
    ports:
      - "10050:10050"
    environment:
      - ZBX_HOSTNAME=client_1
      - ZBX_SERVER_HOST=app
    depends_on:
      - app
  client_2:
    image: zabbix/zabbix-agent:ubuntu-3.0-latest
    environment:
      - ZBX_HOSTNAME=client_2
      - ZBX_SERVER_HOST=app
    depends_on:
      - app
  client_3:
    image: zabbix/zabbix-agent:ubuntu-3.0-latest
    environment:
      - ZBX_HOSTNAME=client_3
      - ZBX_SERVER_HOST=app
    depends_on:
      - app
  client_4:
    image: zabbix/zabbix-agent:ubuntu-3.0-latest
    environment:
      - ZBX_HOSTNAME=client_4
      - ZBX_SERVER_HOST=proxy
    depends_on:
      - proxy
  client_5:
    image: zabbix/zabbix-agent:ubuntu-3.0-latest
    environment:
      - ZBX_HOSTNAME=client_5
      - ZBX_SERVER_HOST=proxy
    depends_on:
      - proxy
  ftp_server:
    image: ustclug/ftp
