version: '2'
services:
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix
    networks:
      app_net:
        ipv4_address: 172.16.238.3
  app:
    build: .
    environment:
      - DB_SERVER_HOST=db
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
    ports:
      - "10051:10051"
    depends_on:
      - db
    networks:
      app_net:
        ipv4_address: 172.16.238.2
  web:
    image: zabbix/zabbix-web-apache-mysql:ubuntu-3.0-latest
    ports:
      - "8080:80"
    environment:
      - DB_SERVER_HOST=db
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - ZBX_SERVER_HOST=app
      - TZ=America/SAO_PAULO
    depends_on:
      - app
    networks:
      app_net:
        ipv4_address: 172.16.238.4
  proxy:
    image: zabbix/zabbix-proxy-sqlite3
    depends_on:
      - app
    environment:
      - ZBX_PROXYMODE=0
      - ZBX_HOSTNAME=zabbix-proxy
      - ZBX_SERVER_HOST=app
      - ZBX_SERVER_PORT=10051
    networks:
      app_net:
        ipv4_address: 172.16.238.5
      proxy_net:
        ipv4_address: 172.16.239.2
  client_1:
    image: zabbix/zabbix-agent:ubuntu-3.0-latest
    ports:
      - "10050:10050"
    environment:
      - ZBX_HOSTNAME=client_1
      - ZBX_SERVER_HOST=app
    depends_on:
      - app
    networks:
      app_net:
        ipv4_address: 172.16.238.6
  client_2:
    image: zabbix/zabbix-agent:ubuntu-3.0-latest
    environment:
      - ZBX_HOSTNAME=client_2
      - ZBX_SERVER_HOST=app
    depends_on:
      - app
    networks:
      app_net:
        ipv4_address: 172.16.238.7
  client_3:
    image: zabbix/zabbix-agent:ubuntu-3.0-latest
    environment:
      - ZBX_HOSTNAME=client_3
      - ZBX_SERVER_HOST=app
    depends_on:
      - app
    networks:
      app_net:
        ipv4_address: 172.16.238.8
  client_4:
    image: zabbix/zabbix-agent:ubuntu-3.0-latest
    environment:
      - ZBX_HOSTNAME=client_4
      - ZBX_SERVER_HOST=proxy
    depends_on:
      - proxy
    networks:
      proxy_net:
        ipv4_address: 172.16.239.3
  client_5:
    image: zabbix/zabbix-agent:ubuntu-3.0-latest
    environment:
      - ZBX_HOSTNAME=client_5
      - ZBX_SERVER_HOST=proxy
    depends_on:
      - proxy
    networks:
      proxy_net:
        ipv4_address: 172.16.239.4
  client_6:
    image: zabbix/zabbix-agent:ubuntu-3.0-latest
    environment:
      - ZBX_HOSTNAME=client_6
      - ZBX_SERVER_HOST=app
    depends_on:
      - app
    networks:
      app_net:
        ipv4_address: 172.16.238.9
  ftp_server:
    image: ustclug/ftp
    networks:
      proxy_net:
        ipv4_address: 172.16.239.5
  http_server:
    image: nginx
    networks:
      proxy_net:
        ipv4_address: 172.16.239.6
  route_1:
    image: polinux/snmpd
    networks:
      app_net:
        ipv4_address: 172.16.238.126
networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
  proxy_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24
        gateway: 172.16.239.1